from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from datetime import datetime, timezone
from typing import List
from app.auth.dependencies import get_current_user
from app.database.connection import get_db
from app.ai.gemini_service import GeminiService
from app.utils.mongo import serialize_doc, serialize_list, to_object_id

router = APIRouter(prefix="/api/roadmaps", tags=["AI Learning Roadmaps"])

class RoadmapRequest(BaseModel):
    goal: str
    weeks: int = 8

@router.post("/generate")
async def generate_roadmap(req: RoadmapRequest, current_user: dict = Depends(get_current_user)):
    """Generate a custom interactive learning roadmap using Gemini AI."""
    db = get_db()
    
    # Generate roadmap weeks using Gemini Service
    weeks_list = await GeminiService.generate_roadmap(req.goal, req.weeks)
    
    new_roadmap = {
        "user_id": to_object_id(current_user["id"]) if db is not None else "dev_user_id",
        "goal": req.goal,
        "weeks": weeks_list,
        "created_at": datetime.now(timezone.utc)
    }
    
    if db is not None:
        result = await db.roadmaps.insert_one(new_roadmap)
        new_roadmap["_id"] = result.inserted_id
        
    return serialize_doc(new_roadmap)

@router.get("/list", response_model=List[dict])
async def list_roadmaps(current_user: dict = Depends(get_current_user)):
    """Retrieve all roadmaps generated by the user."""
    db = get_db()
    if db is None:
        # Development Mock
        return [
            {
                "id": "mock_roadmap_id",
                "goal": "Become Full Stack React Developer",
                "weeks": [
                    {"week_number": 1, "topic": "HTML & CSS Layouts", "objectives": ["Flexbox", "CSS Grid"], "resources": ["MDN Docs"], "completed": True},
                    {"week_number": 2, "topic": "JavaScript & DOM", "objectives": ["Event Listeners", "Fetch API"], "resources": ["JS Info"], "completed": False}
                ],
                "created_at": datetime.now(timezone.utc)
            }
        ]
        
    cursor = db.roadmaps.find({"user_id": to_object_id(current_user["id"])})
    roadmaps = await cursor.to_list(length=50)
    return serialize_list(roadmaps)

@router.put("/{roadmap_id}/toggle/{week_number}")
async def toggle_week(roadmap_id: str, week_number: int, current_user: dict = Depends(get_current_user)):
    """Toggle the completion status of a specific week in the roadmap."""
    db = get_db()
    if db is None:
        return {"status": "success", "message": f"Toggled week {week_number} in development offline mode."}

    roadmap_obj_id = to_object_id(roadmap_id)
    roadmap = await db.roadmaps.find_one({"_id": roadmap_obj_id})
    if not roadmap:
        raise HTTPException(status_code=404, detail="Roadmap not found")

    weeks = roadmap.get("weeks", [])
    updated = False
    for week in weeks:
        if week.get("week_number") == week_number:
            week["completed"] = not week.get("completed", False)
            updated = True
            break
            
    if not updated:
        raise HTTPException(status_code=400, detail="Week number not found in roadmap")
        
    await db.roadmaps.update_one(
        {"_id": roadmap_obj_id},
        {"$set": {"weeks": weeks}}
    )
    
    return {"status": "success", "weeks": weeks}
